FinancialNotepad/Controllers/CategoryController.cs
using FinancialNotepad.Data;
using FinancialNotepad.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinancialNotepad.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger _logger;

        public CategoryController(ApplicationDbContext context, ILogger<CategoryController> logger, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var categories = _context.Categories.Where(q => q.UserId == userId).ToList();
            return View(categories);

        }


        // GET: Category/AddOrEdit
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Category{CategoryId = 0});
            else
                return View(_context.Categories.Find(id));

        }

        // POST: Category/AddOrEdit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("CategoryId,Title,Icon,UserId")] Category category)
        {
            ModelState.Clear();
            //TryValidateModel(category);
            //ModelState.ClearValidationState(nameof(category));

            var userId = _userManager.GetUserId(User);
            category.UserId = userId;

            if (ModelState.IsValid)
            {
                if (category.CategoryId == 0)
                    _context.Add(category);
                else
                    _context.Update(category);
 
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }


        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("No Items in Categories");
            }
            if (id != 1)
            {
                var category = await _context.Categories.FindAsync(id);
                _context.Categories.Remove(category);

                await _context.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

FinancialNotepad/Controllers/EconomyController.cs
using FinancialNotepad.ViewModels;
using MathExpressionConstructor;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace FinancialNotepad.Controllers
{
    public class EconomyController : Controller
    {
        public ParserMain _expParser = new ParserMain();

        public IActionResult Index()
        {
            return View(new EconomyMetrics());
        }

        [HttpPost]
        public async Task<IActionResult> Calculate(EconomyMetrics ec)
        {
            ec.Profit = ec.Income - ec.Expense;
            ec.MrjIncome = ec.Income - ec.VariableCosts;
            ec.PureProfit = ec.Profit * (100 - ec.CommonTaxPercent) / 100;
            ec.AmDed = (double)ec.AmSumCosts / ec.UsefulPeriod;
            return View("Index",ec);
        }

    }
}

FinancialNotepad/Controllers/StatisticsController.cs
using System.Globalization;
using FinancialNotepad.Data;
using FinancialNotepad.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinancialNotepad.Controllers
{
    [Authorize]
    public class StatisticsController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public StatisticsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<ActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            DateTime StartDate = DateTime.Today.AddDays(-365);
            DateTime EndDate = DateTime.Today;

            List<Transaction> SelectedTransactions = await _context.Transactions
                .Where(q => q.UserId == userId)
                .Include(x => x.Category)
                .Where(y => y.Date >= StartDate && y.Date <= EndDate)
                .ToListAsync();

            double totalIncome = SelectedTransactions
                .Where(i => i.Type == "Income")
                .Sum(j => j.Amount);
            ViewBag.TotalIncome = totalIncome.ToString("F") + " $";

            double totalExpense = SelectedTransactions
                .Where(i => i.Type == "Expense")
                .Sum(j => j.Amount);
            ViewBag.TotalExpense = totalExpense.ToString("F") + " $";

            var profit = totalIncome - totalExpense;
            CultureInfo culture = CultureInfo.CreateSpecificCulture("en-US");
            culture.NumberFormat.CurrencyNegativePattern = 1;
            ViewBag.Profit = String.Format(culture, "{0:F}", profit);

            ViewBag.DoughnutChartData = SelectedTransactions
                .Where(i => i.Type == "Expense")
                .GroupBy(j => j.Category.CategoryId)
                .Select(k => new
                {
                    categoryTitleWithIcon = k.First()?.Category?.Icon + " " + k.First()?.Category?.Title,
                    amount = k.Sum(j => j.Amount),
                    formattedAmount = k.Sum(j => j.Amount).ToString("F") + " $",
                })
                .OrderByDescending(l => l.amount)
                .ToList();


            List<PlotData> incomeStatistics = SelectedTransactions
                .Where(i => i.Type == "Income")
                .GroupBy(j => j.Date)
                .Select(k => new PlotData()
                {
                    day = k.First().Date.ToString("dd-MM-yyyy"),
                    income = k.Sum(l => l.Amount)
                })
                .ToList();

            List<PlotData> expenseStatistics = SelectedTransactions
                .Where(i => i.Type == "Expense")
                .GroupBy(j => j.Date)
                .Select(k => new PlotData()
                {
                    day = k.First().Date.ToString("dd-MM-yyyy"),
                    expense = k.Sum(l => l.Amount)
                })
                .ToList();

            string[] LastData = Enumerable.Range(0, 365)
                .Select(i => StartDate.AddDays(i).ToString("dd-MM-yyyy"))
                .ToArray();

            ViewBag.SplineChartData = 
                    from day in LastData
                    join income in incomeStatistics on day equals income.day into dayIncomeJoined
                    from income in dayIncomeJoined.DefaultIfEmpty()
                    join expense in expenseStatistics on day equals expense.day into expenseJoined
                    from expense in expenseJoined.DefaultIfEmpty()
                    select new
                    {
                        day = day,
                        income = income == null ? 0 : income.income,
                        expense = expense == null ? 0 : expense.expense,
                    };

            ViewBag.RecentTransactions = await _context.Transactions
                .Where(q => q.UserId == userId)
                .Include(i => i.Category)
                .OrderByDescending(j => j.Date)
                .Take(5)
                .ToListAsync();

            return View();
        }
    }

    public class PlotData
    {
        public string day;
        public double income;
        public double expense;

    }
}

FinancialNotepad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinancialNotepad</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.syncfusion.com/ej2/20.1.55/bootstrap5.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/FinancialNotepad.styles.css" asp-append-version="true" />
    <script src="https://cdn.syncfusion.com/ej2/20.1.55/dist/ej2.min.js"></script>
</head>
<body style="height: auto">
    <div class="main-app-body">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom nav-shadowed mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Finance Management</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transactions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a>
                            </li>

                            @if (User.IsInRole("Accountant"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Economy" asp-action="Index">Metrics</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="">Administration</a>
                                </li>
                            }
                            
                        </ul>
                        <partial name="_LoginPartial"/>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <main role="main" class="pb-4">
                        <div>
                            

                        </div>
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
        <!--
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - FinancialNotepad - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        -->
    </div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
<ejs-scripts></ejs-scripts>
</body>
</html>